Fix shape conservative advancement normal computation
flexible-collision-library/fcl pull request #505
Opened 2020-10-22 07:37 UTC by ddengster

Related issue: https://github.com/flexible-collision-library/fcl/issues/501

This PR fixes the frame of reference for computation of points while doing conservative advancement for shapes. There's also an additional test for collisions with splines made from rotated points. If any reviewer/maintainer could advise me on where to place the test please do so!

2020-10-22 16:02 UTC, SeanCurtis-TRI reviewed
+@seancurtis-tri for feature review.

> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-:-MKG229KElgF8TQOqwbZ:bax1t9m)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @SeanCurtis-TRI)



<!-- Sent from Reviewable.io -->

2020-10-22 16:31 UTC, SeanCurtis-TRI requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ddengster and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MKG4ZUCBi1HPBTNcuLR:-MKG4ZUCBi1HPBTNcuLS:b-u59066) (no related file):*
You've got windows CI failure. In three of the configurations, the test is simply failing (i.e., no collision reported). In the 32-bit release version, we're actually getting an SEH exception which tells me there are some more fundamental issues at play here. I certainly can't find any other reference to `SplineMotion` in the `test` directory, which suggests that we have no evidence that it was every particularly happy under windows.  :-/  Welcome to the headache of FCL PRs -- lots of supported platforms.  :)

Let me know if you need help trying to figure out what's going on.

---
___
*[include/fcl/narrowphase/detail/traversal/distance/shape_conservative_advancement_traversal_node-inl.h, line 79 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MKG8Qgn5gjLGLtlkSmo:-MKG8Qgn5gjLGLtlkSmp:b3jkck0) ([raw file](https://github.com/flexible-collision-library/fcl/blob/27adf8608faa46061d5ddc2b94680df5ee4844ab/include/fcl/narrowphase/detail/traversal/distance/shape_conservative_advancement_traversal_node-inl.h#L79)):*
> ```objc
>   this->nsolver->shapeDistance(*(this->model1), this->tf1, *(this->model2), this->tf2, &distance, &closest_p1, &closest_p2);
> 
>   Vector3<S> n = closest_p2 - closest_p1;
> ```

BTW I don't know about you, but I was surprised that this appears the only aspect of the infrastructure that suffered from this problem. I dug a bit and found nothing.
___
*[test/test_fcl_collision.cpp, line 123 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MKG7s1BAPMdXBbxhXEF:-MKG7s1BAPMdXBbxhXEG:bivfe6k) ([raw file](https://github.com/flexible-collision-library/fcl/blob/27adf8608faa46061d5ddc2b94680df5ee4844ab/test/test_fcl_collision.cpp#L123)):*
> ```cpp
>     r[0], r[1], r[2], r[3]);
> 
>   // test collision with unit circles
> ```

nit: Could you capitalize "Test", add a period to the end, and swap "circles" for "spheres", please.
___
*[test/test_fcl_collision.cpp, line 142 at r1](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MKG7kUL1C-RQqE4B00P:-MKG7kUL1C-RQqE4B00Q:blid4pf) ([raw file](https://github.com/flexible-collision-library/fcl/blob/27adf8608faa46061d5ddc2b94680df5ee4844ab/test/test_fcl_collision.cpp#L142)):*
> ```cpp
> 
>   EXPECT_TRUE(result.is_collide);
> ```

nit: extra vertical whitespace. Please delete this empty line.


<!-- Sent from Reviewable.io -->

2020-10-22 18:41 UTC, SeanCurtis-TRI reviewed
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505)* status: all files reviewed, 4 unresolved discussions (waiting on @ddengster)



<!-- Sent from Reviewable.io -->

2020-10-26 07:45 UTC, ddengster commented
> You've got windows CI failure. In three of the configurations, the test is simply failing (i.e., no collision reported). In the 32-bit release version, we're actually getting an SEH exception which tells me there are some more fundamental issues at play here. I certainly can't find any other reference to SplineMotion in the test directory, which suggests that we have no evidence that it was every particularly happy under windows. :-/ Welcome to the headache of FCL PRs -- lots of supported platforms. :)


I'm building all the libraries/tests on windows x64 Debug and have found out that it's something to do with eigen.
These are the results:

eigen v3.1 - does not compile
eigen v3.2 - gives me the same test failure. I'm guessing this is likely what the CI uses.
eigen v3.3 - works, no test failure.

Perhaps we should up the required eigen versions with this PR?

On a side note, can someone let me know of a hassle-free setup that is able to build fcl + libccd + eigen on windows? If ; right now I'm literally referencing the CI logs for commands and copying dlls to make things work.

2020-10-26 13:23 UTC, SeanCurtis-TRI requested changes
Re: windows and FCL - sadly I'm in the same boat. I rarely go near it, and when I do, I go through similar hoops that you are jumping through. Sorry 'bout that.

As for the error, see my note below about alignment.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-:-MK_3ptU8wyEQ49wPB1Q:bhifzui)* status: all files reviewed, 5 unresolved discussions (waiting on @ddengster)

*[a discussion](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MKG4ZUCBi1HPBTNcuLR:-MK_31vL5CEQcT4_hcDz:b-hx0lxv) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

You've got windows CI failure. In three of the configurations, the test is simply failing (i.e., no collision reported). In the 32-bit release version, we're actually getting an SEH exception which tells me there are some more fundamental issues at play here. I certainly can't find any other reference to `SplineMotion` in the `test` directory, which suggests that we have no evidence that it was every particularly happy under windows.  :-/  Welcome to the headache of FCL PRs -- lots of supported platforms.  :)

Let me know if you need help trying to figure out what's going on.
</blockquote></details>

In the [Debug, windows 32 report](https://ci.appveyor.com/project/flexible-collision-library/fcl/builds/35948836/job/yvl66jf0ovide480), it's providing a classic alignment error:

```
Assertion failed: (reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"
```

Glancing quickly at the test, I didn't see any obvious offenders. I'm inclined to believe it might actually be in the tested class (and given the paucity of unit tests on these classes, that suggests better than even odds). Somewhere, we're storing some structure that requires alignment but isn't getting it.

---
*[a discussion](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MK_3Sl65fwi0h4c-SSo:-MK_3Sl72jy_xqqx_xlP:b-941udy) (no related file):*
We're using Reviewble for code review. After addressing a reviewer comment, you should indicate so on the comment.

Any comment with the prefix: "nit", "minor", "fyi", or "btw" can be simply resolved by typing "done" (or just hitting the "Acknowledge" button.

There are actually more semantic conventions, but for now, that's sufficient.

---


<!-- Sent from Reviewable.io -->

2020-10-28 05:05 UTC, ddengster reviewed
so commit 10e12cc tries to get the numbers synced up and correct, and it's passing the x64 windows builds. I've tracked it down to the normalize function which was not ignoring zero length vectors before normalizing. This issue https://gitlab.com/libeigen/eigen/-/issues/977 points to a fix in 3.3, but the windows CI is using 3.2.9 hence the test failure. Still, this raises the question on whether or not the CI should be updated to eigen 3.3.

Regarding the failing windows 32bit builds I havent gotten around to compiling them yet, so wait for it.

> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-:-MKh_qdG5GjHImgKVRod:b-m4sl60)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @ddengster and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MK_3Sl65fwi0h4c-SSo:-MKhYuO66cQZONr1a09l:b-896fix) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

We're using Reviewble for code review. After addressing a reviewer comment, you should indicate so on the comment.

Any comment with the prefix: "nit", "minor", "fyi", or "btw" can be simply resolved by typing "done" (or just hitting the "Acknowledge" button.

There are actually more semantic conventions, but for now, that's sufficient.
</blockquote></details>

Done.

---


<!-- Sent from Reviewable.io -->

2020-10-28 13:29 UTC, traversaro commented
> On a side note, can someone let me know of a hassle-free setup that is able to build fcl + libccd + eigen on windows? 

I typically use [vcpkg](https://github.com/Microsoft/vcpkg) to install the dependencies of a project I need to use/run tests, and I never had too many problems.

2020-11-20 07:44 UTC, ddengster commented
*[a discussion](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MKG4ZUCBi1HPBTNcuLR:-MMZVvRA4OugxJ9RTyky:bn4n7gv) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In the [Debug, windows 32 report](https://ci.appveyor.com/project/flexible-collision-library/fcl/builds/35948836/job/yvl66jf0ovide480), it's providing a classic alignment error:

```
Assertion failed: (reinterpret_cast<size_t>(array) & 0xf) == 0 && "this assertion is explained here: " "http://eigen.tuxfamily.org/dox-devel/group__TopicUnalignedArrayAssert.html" " **** READ THIS WEB PAGE !!! ****"
```

Glancing quickly at the test, I didn't see any obvious offenders. I'm inclined to believe it might actually be in the tested class (and given the paucity of unit tests on these classes, that suggests better than even odds). Somewhere, we're storing some structure that requires alignment but isn't getting it.
</blockquote></details>

i've switched from shared_ptr to use make_aligned_shared to fix the alignment error. The problem stems from this issue(https://gitlab.com/libeigen/eigen/-/issues/1049) with eigen v3.2 

---


<!-- Sent from Reviewable.io -->

2020-11-20 14:57 UTC, SeanCurtis-TRI requested changes
One math nit, but this looks basically there.

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-:-MMa93rN9g0DVDYSV3tH:bx3p5of)* status: all files reviewed, 2 unresolved discussions (waiting on @ddengster)

*[a discussion](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MK_3Sl65fwi0h4c-SSo:-MMa98u7BoTLb74TIcvS:b322z61) (no related file):*
<details><summary><i>Previously, ddengster wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Don't forget to hit "Acknowledge" or type "done". I went ahead and marked myself satisified on the comments you'd addressed but hadn't closed out.

---
___
*[include/fcl/math/motion/spline_motion-inl.h, line 128 at r3](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MMa7ZQ35XjaUmWr4Edi:-MMa7ZQ35XjaUmWr4Edj:bg1cbjs) ([raw file](https://github.com/flexible-collision-library/fcl/blob/6de77301852d56d1f5ff2725a7d46cf019a7ff4e/include/fcl/math/motion/spline_motion-inl.h#L128)):*
> ```objc
>   Vector3<S> cur_w = Rd[0] * getWeight0(dt) + Rd[1] * getWeight1(dt) + Rd[2] * getWeight2(dt) + Rd[3] * getWeight3(dt);
>   S cur_angle = cur_w.norm();
>   if (cur_w.squaredNorm() > 0.0)
> ```

nit I believe his would be much better as:

```c++
S cur_angle = cur_w.norm();
if (cur_angle > 0.0) {
   cur_w /= cur_angle;
}
```

As it is, you're paying the cost for two redundant dot products and one redundant square root.


<!-- Sent from Reviewable.io -->

2020-11-23 02:46 UTC, ddengster commented
*[a discussion](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MK_3Sl65fwi0h4c-SSo:-MMmz8nt-oIOtmRozDNH:bb7f2mf) (no related file):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Don't forget to hit "Acknowledge" or type "done". I went ahead and marked myself satisified on the comments you'd addressed but hadn't closed out.
</blockquote></details>

done

---


<!-- Sent from Reviewable.io -->

2020-11-23 16:44 UTC, SeanCurtis-TRI approved these changes
+@sherm1 Would you like to take a quick look?

<img class="emoji" title=":LGTM:" alt=":LGTM:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-:-MMpzMKVCUjKSUsbvFFk:bjnj3hl)* status: all files reviewed, 1 unresolved discussion (waiting on @ddengster and @sherm1)



<!-- Sent from Reviewable.io -->

2020-11-23 16:44 UTC, SeanCurtis-TRI approved these changes
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @sherm1)



<!-- Sent from Reviewable.io -->

2020-11-23 17:16 UTC, sherm1 approved these changes
Thanks, @ddengster! <img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> with one suggestion below.

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-:-MMq5f-pE1O9dz_L58sb:b-tstr6c)* status: all files reviewed, 1 unresolved discussion (waiting on @ddengster)

___
*[include/fcl/narrowphase/detail/traversal/distance/shape_conservative_advancement_traversal_node-inl.h, line 81 at r4](https://reviewable.io/reviews/flexible-collision-library/fcl/505#-MMq4NN54ohgGp6Yzp9r:-MMq4NN62nop6OkmFPR1:b5hhifd) ([raw file](https://github.com/flexible-collision-library/fcl/blob/554d3ab6e9eac4b76de458338a0900d101419eb9/include/fcl/narrowphase/detail/traversal/distance/shape_conservative_advancement_traversal_node-inl.h#L81)):*
> ```objc
>   Vector3<S> n = closest_p2 - closest_p1;
>   if (n.squaredNorm() > 0.0)
>     n.normalize();
> ```

BTW could avoid the redundant dot product with
```c++
const S norm_sq = n.squaredNorm();
if (norm_sq > 0.0)
    n /= sqrt(norm_sq);  // Normalize.
```


<!-- Sent from Reviewable.io -->

2020-11-24 17:32 UTC, sherm1 approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505)* status: all files reviewed, 1 unresolved discussion (waiting on @ddengster)



<!-- Sent from Reviewable.io -->

2020-11-24 17:33 UTC, sherm1 approved these changes
> *[Reviewable](https://reviewable.io/reviews/flexible-collision-library/fcl/505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ddengster)



<!-- Sent from Reviewable.io -->

2020-11-24 17:34 UTC, merged